### ISSUE TITLE
Setup instructions fail

### ISSUE THREAD

**Issue by qznc** [ixtreon/ml-market#4]
I made myself [a Makefile for an easier setup](https://github.com/qznc/ml-market/commit/cd8cc2ec863673d2c526a1c425391ae362418794).

However, it does not work yet. What I do on my Ubuntu 14.04 LTS is:

    $ make shell
    $ python manage.py makemigrations

Which then fails with various errors and warnings. See [log.txt](https://github.com/ixtreon/ml-market/files/31179/log.txt).

**Comment by ixtreon** [comment]
Hi,

It took me some digging but the cause is a `markets.cron` object getting created every time the `manage.py` script is invoked. The cron instance then tries to update the state of all markets in the db which fails since there are no market tables to begin with. It also makes the `manage.py` script completely useless unless you have the correct schema in place. 

Please see if the fix I submitted solves the issue for you.

**Comment by qznc** [comment]
Yes, issue is fixed. Thanks!
